# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZwKKrsJQRSo7zK9_fEEZHQXEPszIXCqz
"""

import streamlit as st
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

# ------------------ PAGE CONFIG ------------------
st.set_page_config(
    page_title="💧 Water Quality Predictor",
    page_icon="💧",
    layout="centered"
)

# ------------------ TITLE ------------------
st.markdown(
    """
    <h1 style='text-align: center; color: #00BFFF;'>
    💧 Water Quality Prediction System
    </h1>
    <p style='text-align: center;'>
    Predict Dissolved Oxygen (DO) & Water Safety using Machine Learning
    </p>
    """,
    unsafe_allow_html=True
)

# ------------------ LOAD DATA ------------------
@st.cache_data
def load_data():
    data = pd.read_csv("water_quality_data.csv")
    return data

try:
    data = load_data()
except Exception as e:
    st.error("❌ Error loading dataset. Make sure 'water_quality_data.csv' is in the same folder.")
    st.stop()

# ------------------ MODEL TRAINING ------------------
@st.cache_resource
def train_model(data):
    X = data[['pH', 'Turbidity', 'Temperature']]
    y = data['DO']

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    model = RandomForestRegressor(n_estimators=100)
    model.fit(X_train, y_train)

    accuracy = r2_score(y_test, model.predict(X_test))

    return model, accuracy

model, accuracy = train_model(data)

# ------------------ SIDEBAR ------------------
st.sidebar.header("📊 Model Info")
st.sidebar.write(f"**Algorithm:** Random Forest")
st.sidebar.write(f"**Accuracy (R²):** {round(accuracy, 2)}")

# ------------------ USER INPUT ------------------
st.subheader("🔍 Enter Water Parameters")

col1, col2, col3 = st.columns(3)

with col1:
    ph = st.slider("pH Level", 0.0, 14.0, 7.0)

with col2:
    turbidity = st.slider("Turbidity (NTU)", 0.0, 100.0, 20.0)

with col3:
    temperature = st.slider("Temperature (°C)", 0.0, 50.0, 25.0)

# ------------------ PREDICTION ------------------
if st.button("🚀 Predict Water Quality"):

    try:
        sample = [[ph, turbidity, temperature]]
        prediction = model.predict(sample)[0]

        # Determine Status
        if prediction >= 6:
            status = "SAFE ✅"
            color = "green"
        elif prediction >= 4:
            status = "WARNING ⚠️"
            color = "orange"
        else:
            status = "UNSAFE ❌"
            color = "red"

        # ------------------ OUTPUT ------------------
        st.markdown("### 📈 Prediction Result")

        st.metric(label="Predicted DO (mg/L)", value=round(prediction, 2))

        st.markdown(
            f"<h3 style='color:{color};'>Water Status: {status}</h3>",
            unsafe_allow_html=True
        )

    except Exception as e:
        st.error("❌ Prediction failed. Check inputs or model.")

# ------------------ FOOTER ------------------
st.markdown("---")
st.markdown(
    "<p style='text-align: center;'>Built with ❤️ using Streamlit</p>",
    unsafe_allow_html=True
)