# -*- coding: utf-8 -*-
"""Random forest ML model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PPNx2FzOhQe5XL6yyjJSWxQVekm6Wih6
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
# Get the name of the first uploaded file
file_name = list(uploaded.keys())[0]
data = pd.read_csv(file_name)
data.head()

import os
os.listdir()
import pandas as pd

data = pd.read_csv("water_quality_data.csv")
data.head()

X = data[['pH', 'Turbidity', 'Temperature']]
y = data['DO']

X = data[['pH', 'Turbidity', 'Temperature']]
y = data['DO']

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestRegressor(n_estimators=100)
model.fit(X_train, y_train)

sample = [[7.2, 20, 27]]
prediction = model.predict(sample)

print("Predicted DO:", prediction[0])

from sklearn.metrics import r2_score

# Predict on test data
predictions = model.predict(X_test)

# Calculate accuracy (R² score)
print("Accuracy:", r2_score(y_test, predictions))

print("Predicted DO:", prediction[0])

predicted_DO = prediction[0]

if predicted_DO >= 6:
    status = "SAFE"
elif predicted_DO >= 4:
    status = "WARNING"
else:
    status = "UNSAFE"

print("Predicted DO:", round(predicted_DO,2), "mg/L")
print("Water Status:", status)

# UNSAFE SAMPLE
import pandas as pd

sample = pd.DataFrame([[6.3, 60, 34]],
                      columns=['pH', 'Turbidity', 'Temperature'])

prediction = model.predict(sample)
predicted_DO = prediction[0]

print("Predicted DO:", round(predicted_DO, 2))

if predicted_DO < 5.5:
    print("Water Status: UNSAFE")
else:
    print("Water Status: SAFE")